[package]
name = "test-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
smol = "2.0.2"
surf = "2.3.2"
toml = "0.9.2"
